name: linkify
description: Low-level link (text, URLs, emails, user tagging) parsing library in Dart.
version: 4.1.0
homepage: https://github.com/Cretezy/linkify

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  collection: ^1.0.0
  flutter_lints: ^2.0.1
  test: ^1.0.0
